### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by xElkomy** [rusty-sec/lotus#37]
Hello, When I was trying to install the tool, I got an error 
![image](https://user-images.githubusercontent.com/46958133/197059970-b73a1cdd-c580-43b5-8b52-571c67a2d88a.png)

But I don't have enough knowledge to figure out what happened, and what is the solution are you can help me with that?

**Comment by knassar702** [comment]
hey @xElkomy, this issue is because of the git submodule that I added for the future but I forgot to remove it from the master branch
I've deleted it now , can you please re-install it

Also if you need to try the beta version without compiling the code you can download the binary file from release page


best regards
@knassar702
